[connections.snowflake]
user = "Nandia"
password = "Nandinbold123!"
account = "do04924.ap-southeast-1"
warehouse = "cdna_wh_s"
database = "CDNA_HR_DATA"
schema = "SKYTEL"
role = "survey_role"
[users]
hr = "demo123"
Amarsanaa = "8dK3mZ1r"
Bayarzul = "T7wLx2eQ"
Bayarchimeg = "zR3n8KpM"
Buyandari = "Yt29qLmC"
Belgute = "qX5rN3wz"
Zoljargal = "m7ZpK1Ra"
Ichinkhorloo = "A3bX2nZ9"
Munguntuya = "W9rLm7Qy"
Munguntsetseg = "hT1cX8oZ"
Munkhnaran = "K2Lp9zQm"
Munkhsansar = "fR6zTq2Y"
Myagmarsuren = "Z4xYw7Kr"
Narantuya = "pM3vK9xT"
Nomin.A = "eQ7Nz8Wr"
Nomin.J = "tX4Rm2Yz"
Khulan = "B7qWz9Km"
Khenchbish = "xP6mZ1rT"
Tsendayush = "Lm8qRt5Y"
Chantsaldulam = "R2nXw9zK"
